### ISSUE TITLE
Missing flask feature: from Flask import Response

### ISSUE THREAD

**Issue by Xd-pro** [replit/replit-py#83]
I was running into MIME type issues. I could solve them fine in flask using:
`Response("Response Text", mimetype="text/css")`
I can't do this in the fork of flask included in this module.

Edit: My import gives an error when like this:
`from replit.web import Response`

**Comment by Xd-pro** [comment]
Temporary fix:

1. Add `flask = "^1.1.2"` to pyproject.toml under `[tool.poetry.dependencies]`
2. Use `from flask import Response`

**Comment by Scoder12** [comment]
This library isn't meant to be a fork of flask, instead it just provides a few utilities that build on top of flask. If there is something that is not in the library importing from flask directly is the intended solution. 

With that said, `Response` is common enough that it could be useful to import it inside the library so that `from replit.web import Response` works correctly.

**Comment by Scoder12** [comment]
Adding many aliases like this isn't a priority for the library as it is impossible to support all of them.
