### ISSUE TITLE
Accessing the DB from outside repl.it

### ISSUE THREAD

**Issue by Hunter2807** [replit/replit-py#89]
Hey! 

I was making an app, and I wanted to use the repl db to save data... The app would be an Android app, and not a repl.it app. Is there a way to access the db **from** the Android app? 

Thanks in Advance!

**Comment by Scoder12** [comment]
You can make a repl that proxies requests to the database. This is actually a common usecase so it has been added to the library in the `replit.database.server` module. You can also roll your own proxy if you want to add some sort of authentication so that random people can't view/change your DB contents.
